application: nofrilzblog
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: css

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /error
  static_files: static_page/error.html
  upload: static/error.html

- url: /.*
  script: main_servelet.py
